loader="uefi"

graphics="yes"
graphics_port="5903"
graphics_listen="127.0.0.1"
graphics_res="1280x720"

xhci_mouse="yes"

cpu=2
cpu_sockets=1
cpu_cores=2
cpu_threads=1

memory=6G

# put up to 8 disks on a single ahci controller.
# without this, adding a disk pushes the following network devices onto higher slot numbers,
# which causes windows to see them as a new interface
ahci_device_limit="8"

# ideally this should be changed to virtio-net and drivers installed in the guest
# e1000 works out-of-the-box
#network0_type="virtio-net"
network0_type="e1000"
network0_switch="public"

disk0_type="nvme"
disk0_name="disk0.img"

utctime="no"
bhyve_options="-s 8,hda,play=/dev/dsp,rec=/dev/dsp"

uuid="b30d20dd-9bbd-11f1-8cbf-3c970e8fcc97"
network0_mac="58:9c:fc:0c:45:fa"
